language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install coveralls flake8
  - python setup.py install
script:
  - flake8 rbcz
  - python -W always setup.py test
  - coverage run --source=rbcz setup.py test
after_success:
  - coveralls